import { useRouter } from 'next/router';
import { Stack, Button, Flex } from "@chakra-ui/react";
import {
  collection,
  getDocs,
  limit,
  orderBy,
  query,
  where,
} from "firebase/firestore";
import { motion } from "framer-motion";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useAuthState } from "react-firebase-hooks/auth";

import { Post, PostVote } from "../atoms/PostAtom";
import CreatePostLink from "../components/Community/CreatePostLink";
import PersonalHome from "../components/Community/PersonalHome";
import Premium from "../components/Community/Premium";
import Recommendation from "../components/Community/Recommendation";
import PageContent from "../components/Layout/PageContent";
import PostItem from "../components/posts/PostItem";
import PostLoader from "../components/posts/PostLoader";
import { auth, firestore } from "../firebase/clientApp";
import useCommunityData from "../hooks/useCommunityData";
import usePosts from "../hooks/usePosts";

const Home: NextPage = () => {
  const [user, loadingUser] = useAuthState(auth);
  const [loading, setLoading] = useState(false);
  const {
    postStateValue,
    setPostStateValue,
    onDeletePost,
    onSelectPost,
    onVote,
  } = usePosts();
  const { communityStateValue } = useCommunityData();

  const router = useRouter();

  //const communityStateValue = useRecoilValue(CommunityState);

  const buildUserHomeFeed = async () => {
    try {
      if (communityStateValue.mySnippets.length) {
        const myCommunityIds = communityStateValue.mySnippets.map(
          (snippet) => snippet.communityId
        );

        const postQuery = query(
          collection(firestore, "posts"),
          where("communityId", "in", myCommunityIds),
          limit(10)
        );

        const postDoc = await getDocs(postQuery);
        const posts = postDoc.docs.map((doc) => ({
          id: doc.id,
          ...doc.data(),
        }));

        setPostStateValue((prev) => ({
          ...prev,
          posts: posts as Post[],
        }));
      } else {
        buildUserHomeFeed();
      }
    } catch (error) {
      console.log("Building HHome Error", error);
    }
  };
  const buildNoUserHomeFeed = async () => {
    setLoading(true);
    try {
      const postQuery = query(
        collection(firestore, "posts"),
        orderBy("voteStatus", "desc")
        //limit(10)
      );

      const postDocs = await getDocs(postQuery);
      const posts = postDocs.docs.map((doc) => ({ id: doc.id, ...doc.data() }));

      setPostStateValue((prev) => ({
        ...prev,
        posts: posts as Post[],
      }));
    } catch (error) {
      console.log("BuildNoUserHome", error);
    }
    setLoading(false);
  };

  const getUserPostVotes = async () => {
    try {
      const postIds = postStateValue.posts.map((post) => post.id);

      const batches: PostVote[] | any[][] = [];

      while (postIds.length) {
        const batch = postIds.splice(0, 10);

        const postVotesQuery = query(
          collection(firestore, `users/${user?.uid}/postVotes`),
          where("postId", "in", [...batch])
        );
        const postVoteDoc = await getDocs(postVotesQuery);

        const postVotes = postVoteDoc.docs.map((doc: any) => ({
          id: doc.id,
          ...doc.data(),
        }));

        batches.push(postVotes as any);
      }

      setPostStateValue((prev) => ({
        ...prev,
        postVotes: batches.flat() as PostVote[],
      }));
    } catch (error) {
      console.log("getUserPostVotes Error", error);
    }
  };

  useEffect(() => {
    if (communityStateValue.snippetsFetched) buildNoUserHomeFeed();
  }, [communityStateValue.snippetsFetched]);

  useEffect(() => {
    if (!user && !loadingUser) buildNoUserHomeFeed();
  }, [user, loadingUser]);

  useEffect(() => {
    if (user && postStateValue.posts.length) getUserPostVotes();

    return () => {
      setPostStateValue((prev) => ({
        ...prev,
        postVotes: [],
      }));
    };
  }, [user, postStateValue.posts]);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
    >
      <Head>
        <title>Reddit Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/header.png" />
      </Head>
      <PageContent>
        <>
          <Flex justify="center" align="center" width="100%" mb={4}>
            <Button
              colorScheme="blue"
              size="lg"
              width={{ base: "90%", md: "60%", lg: "40%" }}
              borderRadius="md"
              fontWeight="bold"
              fontSize="md"
              onClick={() => {
                if (!user) {
                  setAuthModelState({ open: true, view: "login" });
                  return;
                }
                // If user has communities, use the first one
                const firstCommunityId = communityStateValue.mySnippets?.[0]?.communityId;
                if (firstCommunityId) {
                  router.push(`/r/${firstCommunityId}/submit`);
                } else {
                  // Optionally, show a message or modal to prompt user to join a community
                  alert("Please join a community first!");
                }
              }}
            >
              Ask New Question
            </Button>
          </Flex>
          {loading ? (
            <PostLoader />
          ) : (
            <Stack justifyContent="center">
              {postStateValue.posts.map((post) => (
                <PostItem
                  key={post.id}
                  post={post}
                  onVote={onVote}
                  onDeletePost={onDeletePost}
                  userVoteValue={
                    postStateValue.postVotes.find(
                      (item) => item.postId === post.id
                    )?.voteValue
                  }
                  userIsCreator={user?.uid === post.creatorId}
                  onSelectPost={onSelectPost}
                  homePage
                />
              ))}
            </Stack>
          )}
        </>
        <Stack spacing={5}>
          {/* <Recommendation />
          <Premium />
          <PersonalHome /> */}
        </Stack>
      </PageContent>
    </motion.div>
  );
};

export default Home;